### ISSUE TITLE
User can add a recipe

### ISSUE THREAD

**Issue by Raphael-Cruzado** [Raphael-Cruzado/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a recipe and append to the entries page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user inputs an ingredient item, the item appends to the page immediately and can be deleted. User can also add an image URL to the image placeholder.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/57853350/164059937-08fb65fe-32cb-4bef-8676-84a3801e9927.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="entry-form"]` to the HTML.
- [x] Add a form for creating a journal entry to the `div[data-view="entry-form"]`.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the journal entry form `required`.
- [x] When user inputs an item, append it directly onto the page
- [x] Listen for `'input'` events on the `photoUrl` input to update the `src` attribute of the photo preview when the input value changes.
- [x] Listen for `'submit'` events on the journal entry form and:
  - [x] Put the form's input values into a new object.
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the image preview's `src' attribute.
  - [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing `entryId`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
