### ISSUE TITLE
User can view all their entries

### ISSUE THREAD

**Issue by Raphael-Cruzado** [Raphael-Cruzado/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

When the user submits their entry, it takes them to the entries page where they can view their entries alongside a generated nutrition facts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when user clicks the img they are taken to the specified entry

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/57853350/163910523-92c96b3d-4a68-4c6d-8611-457ec1b7fd15.png)
![image](https://user-images.githubusercontent.com/57853350/163910573-4ce085d6-a8eb-4a6c-8116-ba28da980e5a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 [ ] Add a sibling `div[data-view="entries"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single journal `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Entries.
- [ ] Add an anchor to the entries view that shows the entry form.
- [ ] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [ ] Ensure that submitting a new journal entry automatically shows the `'entries'` view without reloading the page.
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
